/**:
  ros__parameters:
    Kp: 1.5
    Ki: 0.3
    Kd: 0.2
    linear_max: 0.4
    angular_max: 2.0
    linear_min: 0.0
    angular_min: 0.0
    joint1: 90
    joint2: 145
    joint3: 0
    joint4: 0
    joint5: 90
    joint6: 30
    SetArmjoint: false 