# request
string  kin_name
float64[] src_pos
float64[] src_joints
---
# response
float64[] target_joints
float64[] target_pos
float32 x
float32 y
float32 z
float32 roll
float32 pitch
float32 yaw
float32[] joint_1
float32[] joint_2
float32[] joint_3
float32[] joint_4
float32[] joint_5 